local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("TITLE", "DarkTheme")
local Tab = Window:NewTab("TabName")
local Section = Tab:NewSection("Section Name")
Section:UpdateSection("Section New Title")
Section:NewLabel("LabelText")
label:UpdateLabel("New Text")
Section:NewButton("ButtonText", "ButtonInfo", function()
    print("Clicked")
end)
